apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-nginx
  namespace: default
  labels:
    app: react-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-nginx
  template:
    metadata:
      labels:
        app: react-nginx
    spec:
      containers:
        - name: react-nginx
          image: docker.{{server_domain}}/test/react-nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: PROD
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: react-nginx
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: react-nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react-nginx-ingress
  annotations:
  namespace: default
spec:
  rules:
  - host: rnginx.{{cluster_domain}}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: react-nginx
            port: 
              number: 80