---
- name: Set Values
  set_fact:
    venvs:
      # Setup the Kubernetes virtual environment
      - dirname: Kubernetes
        modules:
          - k8s
          - openshift
          - requests
          - docker-compose
        prereqs:
          - gcc

- name: Install python pip
  apt:
    pkg:
    - python3-pip
    - build-essential
    - libssl-dev
    - libffi-dev
    - python3-dev
    - python3-venv
    state: present

- name: "Install pip module required packages"
  apt:
    pkg: "{{ item.prereqs }}"
    state: latest
  loop: "{{ venvs }}"
  when: item.prereqs is defined
  tags:
    - prereq

- name: pip required modules
  pip:
      name: "{{ item.modules }}"
      extra_args: --ignore-installed
  loop: "{{ venvs }}"