---
- name: create data folders
  file:
    path: "{{item}}"
    state: directory
  loop:
  - "{{app_data_dir}}"
  - "{{app_data_dir}}/server"
  - "{{app_data_dir}}/runner"

- include_tasks: init_templates.yml

- name: start
  command: docker-compose -f {{ app_templates_dir }}/docker-compose.yaml up -d

- name: setup admin
  tags:
    - drone-admin
  command: >-
    sqlite3 {{app_data_dir}}/server/database.sqlite \
      "update users set user_admin=true where user_login='{{github_user}}'"
  ignore_errors: yes

## setup reverse-proxy
- name: copy reverse-proxy conf
  ansible.builtin.copy:
    src: "{{ app_templates_dir }}/subdomain.conf"
    remote_src: yes
    dest: "{{reverse_proxy_conf_dir}}/{{server_sub_domain}}.subdomain.conf"
    owner: nobody
    group: users
    mode: u=rw,g=r,o=r

- name: Restart Reverse Proxy {{reverse_proxy_name}}
  command: docker restart {{reverse_proxy_name}}

- include_tasks: cleanup_templates.yml