---
- name: Copy K3d config file
  register: k3d_config
  template:
    src: "k3d-config.yaml"
    dest: ~{{ansible_ssh_user}}/k3d-config.yaml
    owner: root
    group: root
    mode: 0755

- name: Create directory for templates
  file:
    path: ~{{ansible_ssh_user}}/templates
    state: directory
    owner: "{{ansible_ssh_user}}"
    mode: "u=rwx,g=rx,o=" 
    
- name: Create directory for manifests
  file:
    path: ~{{ansible_ssh_user}}/manifests
    state: directory
    owner: "{{ansible_ssh_user}}"
    mode: "u=rwx,g=rx,o="

- name: Copy manifest files
  template:
    src: "{{ item.src }}"
    dest: "~{{ansible_ssh_user}}/manifests/{{ item.dest }}"
    owner: "{{ansible_ssh_user}}"
    mode: "u=rwx,g=rx,o="
  loop:
    - { src: 'manifests/temp-pv.yaml', dest: 'temp-pv.yaml' }
    - { src: 'manifests/temp-pvc.yaml', dest: 'temp-pvc.yaml' }

# - name: Template complete tree
#   template:
#     src: '{{ item.src }}'
#     dest: /web/{{ item.path }}
#     force: yes
#   with_filetree: some/path/
#   when: item.state == 'file'

- name: Create directory for cluster data
  file:
    path: ~{{ansible_ssh_user}}/cluster-data
    state: directory
    owner: "{{ansible_ssh_user}}"
    mode: "u=rwx,g=rx,o="

- name: Create directory .kube
  file:
    path: ~{{ansible_ssh_user}}/.kube
    state: directory
    owner: "{{ansible_ssh_user}}"
    mode: "u=rwx,g=rx,o="

- name: Create Cluster {{ cluster_name }} version k3s:{{ k3s_version }}
  command: >-
    k3d cluster create --config ~{{ansible_ssh_user}}/k3d-config.yaml
      --image "docker.io/rancher/k3s:{{ k3s_version | default(latest) }}"
  changed_when: true

# - name: Copy config file to user home directory
#   copy:
#     src: /etc/rancher/k3s/k3s.yaml
#     dest: ~{{ansible_ssh_user}}/.kube/config
#     remote_src: yes
#     owner: "{{ansible_ssh_user}}"
#     mode: "u=rw,g=,o="

# - name: Replace https://localhost:6443 by https://master-ip:6443
#   command: >-
#     k3s kubectl config set-cluster default
#       --server=https://{{ master_ip }}:6443
#       --kubeconfig ~{{ansible_ssh_user}}/.kube/config
#   changed_when: true    